// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"github.com/epociask/go-rest-api-template/internal/config"
	"github.com/epociask/go-rest-api-template/internal/handlers"
	"github.com/epociask/go-rest-api-template/internal/server"
	"github.com/epociask/go-rest-api-template/internal/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeAndRun(ctx context.Context, cfg config.FilePath) (*server.Server, func(), error) {
	configConfig := config.NewConfig(cfg)
	serverConfig := config.NewServerConfig(configConfig)
	exampleService := service.New()
	exampleHandler, err := handlers.New(exampleService)
	if err != nil {
		return nil, nil, err
	}
	serverServer, cleanup, err := server.New(ctx, serverConfig, exampleHandler)
	if err != nil {
		return nil, nil, err
	}
	return serverServer, func() {
		cleanup()
	}, nil
}

// wire.go:

var serviceModule = wire.NewSet(service.Module, wire.Bind(new(service.Service), new(*service.ExampleService)))

var handlersModule = wire.NewSet(handlers.Module, wire.Bind(new(handlers.Handlers), new(*handlers.ExampleHandler)))
